root = "."
tmp_dir = "storage/log"

[build]
  bin = "build\\builtin-app\\main.exe"
  cmd = "go build -o ./build/builtin-app/ ./cmd/builtin-app/main.go"
  delay = 1000
  exclude_dir = ["asset", "build", "doc", "storage", ".git"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-builtin-app.error.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
