root = "."
tmp_dir = "storage"

[build]
  bin = "build\\web-service\\main.exe"
  cmd = "go build -o ./build/web-service/ ./cmd/web-service/main.go"
  delay = 1000
  exclude_dir = ["asset", "storage", ".git"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-web-service.error.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
