package error

const (
	STATUS_INVALID_DATA     = "INVALID_DATA"
	STATUS_TOO_MANY_REQUEST = "TOO_MANY_REQUEST"
	STATUS_NOT_FOUND        = "NOT_FOUND"
	STATUS_NOT_SUPPORTED    = "NOT_SUPPORTED"
	STATUS_ALREADY_EXISTS   = "ALREADY_EXISTS"
	STATUS_UNKNOWN          = "UNKNOWN"
)
